# Generated by Django 3.0.3 on 2021-02-10 17:56

import chemreg.common.validators
import chemreg.compound.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound', '0001_vega_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecompound',
            name='id',
            field=models.CharField(default=chemreg.compound.utils.build_cid, max_length=50, primary_key=True, serialize=False, unique=True, validators=[chemreg.common.validators.UniqueAcrossModelsValidator(model_list=['substance.Substance'])]),
        ),
    ]
