version: "3.1"

services:
    chemreg-api:
        build:
            context: https://github.com/Chemical-Curation/chemcurator_django.git#${API_BRANCH}
        image: chemreg-django
        restart: unless-stopped
        env_file:
          - .env
        environment:
            CACHE_URL: redis://redis:6379/0
            DATABASE_URL: postgres://pgbouncer:5432/${SQL_DATABASE}
            SECRET_KEY: ${API_SECRET_KEY}
            URL_CONF: api
            WEB_CONCURRENCY: 8
            WHITELIST_CORS: ${SPA_DOMAIN}
            WHITELIST_HOST: ${API_DOMAIN}
        ports:
            - 8000:8000
        depends_on:
          - pgbouncer

    chemreg-admin:
        build:
            context: https://github.com/Chemical-Curation/chemcurator_django.git#${ADMIN_BRANCH}
        image: chemreg-django
        restart: unless-stopped
        env_file:
          - .env
        environment:
            CACHE_URL: redis://redis:6379/1
            DATABASE_URL: postgres://pgbouncer:5432/${SQL_DATABASE}
            SECRET_KEY: ${ADMIN_SECRET_KEY}
            URL_CONF: admin
            WEB_CONCURRENCY: 2
            WHITELIST_HOST: ${ADMIN_DOMAIN}
        ports:
            - 8001:8000
        depends_on:
          - pgbouncer

    redis:
        image: redis:5-alpine
        restart: unless-stopped

    pgbouncer:
        image: pgbouncer/pgbouncer:1.12.0
        restart: unless-stopped
        environment:
            DATABASES_HOST: ${SQL_HOST}
            DATABASES_PASSWORD: ${SQL_PASSWORD}
            DATABASES_PORT: ${SQL_PORT}
            DATABASES_USER: ${SQL_USER}
            PGBOUNCER_LISTEN_PORT: 5432
