version: "3.1"

volumes:
  redisdata:

services:
  chemreg-admin:
    build:
      context: https://github.com/Chemical-Curation/chemcurator_django.git#dev
    image: chemreg
    restart: unless-stopped
    environment:
      ALLOWED_HOSTS: .epa.gov
      CACHE_URL: rediscache://redis:6379/0
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: "false"
      SECRET_KEY: ${SECRET_KEY}
      URL_CONF: admin
      WEB_CONCURRENCY: 1

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    command: redis-server --port 6379 --appendonly yes
