# Generated by Django 3.0.3 on 2021-02-10 20:05

import chemreg.common.validators
import chemreg.substance.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0002_wezn_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='id',
            field=models.CharField(default=chemreg.substance.utils.build_sid, max_length=50, primary_key=True, serialize=False, unique=True, validators=[chemreg.common.validators.UniqueAcrossModelsValidator(model_list=['compound.BaseCompound'])]),
        ),
    ]
